# Generated by Django 5.0 on 2024-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='afaregistration',
            name='occupation',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='afaregistration',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
